name: vendo_certo
description: "Aplicativo de licenciamento com renovação via código."
publish_to: 'none'
version: 1.0.0+20

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependências do Banco de Dados
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

  # Dependência para Hashing de Senha
  crypto: ^3.0.3

  # Dependências do seu projeto (mantidas)
  flutter_pix_pagstar: ^1.0.3
  url_launcher: ^6.1.10
  http: ^1.2.1
  mask_text_input_formatter: ^2.5.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  
  # Dependências do Firebase podem ser adicionadas depois, quando formos fazer o back-end
  # firebase_core: ^3.15.2
  # firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

